-- +goose Up

CREATE TABLE IF NOT EXISTS backups_artifacts (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		status TEXT NOT NULL,
		size_bytes BIGINT,
		checksum TEXT,
		filename TEXT,
		storage_path TEXT,
		error_code TEXT,
		error_message TEXT,
		meta_json JSONB NOT NULL DEFAULT '{}'::jsonb,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	);

CREATE TABLE IF NOT EXISTS backups_runs (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		artifact_id BIGINT,
		status TEXT NOT NULL,
		size_bytes BIGINT,
		checksum TEXT,
		filename TEXT,
		storage_path TEXT,
		error_code TEXT,
		error_message TEXT,
		meta_json JSONB NOT NULL DEFAULT '{}'::jsonb,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (artifact_id) REFERENCES backups_artifacts(id) ON DELETE SET NULL
	);

CREATE TABLE IF NOT EXISTS backups_restore_runs (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		artifact_id BIGINT NOT NULL,
		status TEXT NOT NULL,
		size_bytes BIGINT,
		filename TEXT,
		storage_path TEXT,
		error_code TEXT,
		error_message TEXT,
		meta_json JSONB NOT NULL DEFAULT '{}'::jsonb,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (artifact_id) REFERENCES backups_artifacts(id) ON DELETE RESTRICT
	);

CREATE INDEX IF NOT EXISTS idx_backups_artifacts_created_at ON backups_artifacts(created_at);
CREATE INDEX IF NOT EXISTS idx_backups_artifacts_status ON backups_artifacts(status);
CREATE INDEX IF NOT EXISTS idx_backups_runs_created_at ON backups_runs(created_at);
CREATE INDEX IF NOT EXISTS idx_backups_runs_status ON backups_runs(status);
CREATE INDEX IF NOT EXISTS idx_backups_restore_runs_created_at ON backups_restore_runs(created_at);
CREATE INDEX IF NOT EXISTS idx_backups_restore_runs_status ON backups_restore_runs(status);

-- +goose Down
DROP TABLE IF EXISTS backups_restore_runs;
DROP TABLE IF EXISTS backups_runs;
DROP TABLE IF EXISTS backups_artifacts;
