-- +goose Up

CREATE TABLE IF NOT EXISTS assets (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL,
		type TEXT NOT NULL DEFAULT 'other',
		description TEXT NOT NULL DEFAULT '',
		commissioned_at DATE,
		ip_addresses_json TEXT NOT NULL DEFAULT '[]',
		criticality TEXT NOT NULL DEFAULT 'medium',
		owner TEXT NOT NULL DEFAULT '',
		administrator TEXT NOT NULL DEFAULT '',
		env TEXT NOT NULL DEFAULT 'other',
		status TEXT NOT NULL DEFAULT 'active',
		tags_json TEXT NOT NULL DEFAULT '[]',
		created_by INTEGER,
		updated_by INTEGER,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		version INTEGER NOT NULL DEFAULT 1,
		deleted_at TIMESTAMP
	);

CREATE INDEX IF NOT EXISTS idx_assets_name ON assets(name);
CREATE INDEX IF NOT EXISTS idx_assets_type ON assets(type);
CREATE INDEX IF NOT EXISTS idx_assets_criticality ON assets(criticality);
CREATE INDEX IF NOT EXISTS idx_assets_env ON assets(env);
CREATE INDEX IF NOT EXISTS idx_assets_status ON assets(status);
CREATE INDEX IF NOT EXISTS idx_assets_deleted_at ON assets(deleted_at);
CREATE INDEX IF NOT EXISTS idx_assets_created_at ON assets(created_at);

-- +goose Down

DROP INDEX IF EXISTS idx_assets_created_at;
DROP INDEX IF EXISTS idx_assets_deleted_at;
DROP INDEX IF EXISTS idx_assets_status;
DROP INDEX IF EXISTS idx_assets_env;
DROP INDEX IF EXISTS idx_assets_criticality;
DROP INDEX IF EXISTS idx_assets_type;
DROP INDEX IF EXISTS idx_assets_name;
DROP TABLE IF EXISTS assets;

