-- +goose Up

CREATE TABLE IF NOT EXISTS monitor_sla_policies (
	monitor_id INTEGER PRIMARY KEY,
	incident_on_violation INTEGER NOT NULL DEFAULT 0,
	incident_period TEXT NOT NULL DEFAULT 'day',
	min_coverage_pct REAL NOT NULL DEFAULT 80,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(monitor_id) REFERENCES monitors(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS monitor_sla_period_results (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	monitor_id INTEGER NOT NULL,
	period_type TEXT NOT NULL,
	period_start TIMESTAMP NOT NULL,
	period_end TIMESTAMP NOT NULL,
	uptime_pct REAL NOT NULL DEFAULT 0,
	coverage_pct REAL NOT NULL DEFAULT 0,
	target_pct REAL NOT NULL DEFAULT 0,
	status TEXT NOT NULL DEFAULT 'unknown',
	incident_created INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(monitor_id, period_type, period_start),
	FOREIGN KEY(monitor_id) REFERENCES monitors(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_monitor_sla_results_monitor_period
	ON monitor_sla_period_results(monitor_id, period_type, period_end DESC);
CREATE INDEX IF NOT EXISTS idx_monitor_sla_results_period_end
	ON monitor_sla_period_results(period_end DESC);
CREATE INDEX IF NOT EXISTS idx_monitor_sla_results_status
	ON monitor_sla_period_results(status);

-- +goose Down

DROP INDEX IF EXISTS idx_monitor_sla_results_status;
DROP INDEX IF EXISTS idx_monitor_sla_results_period_end;
DROP INDEX IF EXISTS idx_monitor_sla_results_monitor_period;
DROP TABLE IF EXISTS monitor_sla_period_results;
DROP TABLE IF EXISTS monitor_sla_policies;
