-- +goose Up

ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_secret_enc TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS user_totp_setup (
		user_id INTEGER PRIMARY KEY,
		secret_enc TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		expires_at TIMESTAMP NOT NULL,
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS auth_2fa_challenges (
		id TEXT PRIMARY KEY,
		user_id INTEGER NOT NULL,
		ip TEXT NOT NULL DEFAULT '',
		user_agent TEXT NOT NULL DEFAULT '',
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		expires_at TIMESTAMP NOT NULL,
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
	);

CREATE INDEX IF NOT EXISTS auth_2fa_challenges_user_id_idx ON auth_2fa_challenges(user_id);
CREATE INDEX IF NOT EXISTS auth_2fa_challenges_expires_idx ON auth_2fa_challenges(expires_at);

CREATE TABLE IF NOT EXISTS user_recovery_codes (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		user_id INTEGER NOT NULL,
		code_hash TEXT NOT NULL,
		salt TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		used_at TIMESTAMP,
		used_ip TEXT NOT NULL DEFAULT '',
		used_user_agent TEXT NOT NULL DEFAULT '',
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
	);

CREATE INDEX IF NOT EXISTS user_recovery_codes_user_id_idx ON user_recovery_codes(user_id);
CREATE INDEX IF NOT EXISTS user_recovery_codes_used_at_idx ON user_recovery_codes(used_at);

