-- +goose Up

ALTER TABLE audit_log
  ADD COLUMN IF NOT EXISTS prev_hash TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS event_hash TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS event_sig TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS audit_log_maintenance_guard (
  id INTEGER PRIMARY KEY,
  allow_delete INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO audit_log_maintenance_guard(id, allow_delete, updated_at)
VALUES (1, 0, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS audit_purge_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiated_by TEXT NOT NULL,
  approved_by TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  retention_days INTEGER NOT NULL,
  cutoff_at TIMESTAMP NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  approved_at TIMESTAMP,
  executed_at TIMESTAMP,
  execution_details TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_audit_log_created_id ON audit_log(created_at, id);
CREATE INDEX IF NOT EXISTS idx_audit_log_event_hash ON audit_log(event_hash);
CREATE INDEX IF NOT EXISTS idx_audit_purge_requests_status ON audit_purge_requests(status, created_at);

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION audit_log_no_update() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only';
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION audit_log_no_delete() RETURNS trigger AS $$
DECLARE
  allow_delete_val INTEGER := 0;
BEGIN
  SELECT COALESCE(allow_delete, 0) INTO allow_delete_val FROM audit_log_maintenance_guard WHERE id=1;
  IF allow_delete_val = 1 THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION 'audit_log is append-only';
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

DROP TRIGGER IF EXISTS trg_audit_log_no_update ON audit_log;
CREATE TRIGGER trg_audit_log_no_update
BEFORE UPDATE ON audit_log
FOR EACH ROW EXECUTE FUNCTION audit_log_no_update();

DROP TRIGGER IF EXISTS trg_audit_log_no_delete ON audit_log;
CREATE TRIGGER trg_audit_log_no_delete
BEFORE DELETE ON audit_log
FOR EACH ROW EXECUTE FUNCTION audit_log_no_delete();

-- +goose Down

DROP TRIGGER IF EXISTS trg_audit_log_no_delete ON audit_log;
DROP TRIGGER IF EXISTS trg_audit_log_no_update ON audit_log;
DROP FUNCTION IF EXISTS audit_log_no_delete();
DROP FUNCTION IF EXISTS audit_log_no_update();
DROP INDEX IF EXISTS idx_audit_purge_requests_status;
DROP INDEX IF EXISTS idx_audit_log_event_hash;
DROP INDEX IF EXISTS idx_audit_log_created_id;
DROP TABLE IF EXISTS audit_purge_requests;
DROP TABLE IF EXISTS audit_log_maintenance_guard;

ALTER TABLE audit_log
  DROP COLUMN IF EXISTS event_sig,
  DROP COLUMN IF EXISTS event_hash,
  DROP COLUMN IF EXISTS prev_hash;
