package store

func taskMigrations() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS task_boards (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		organization_id TEXT NOT NULL DEFAULT '',
		name TEXT NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		default_template_id INTEGER,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		is_active INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
	);`,
		`CREATE TABLE IF NOT EXISTS task_board_acl (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		board_id INTEGER NOT NULL,
		subject_type TEXT NOT NULL,
		subject_id TEXT NOT NULL,
		permission TEXT NOT NULL,
		UNIQUE(board_id, subject_type, subject_id, permission),
		FOREIGN KEY(board_id) REFERENCES task_boards(id) ON DELETE CASCADE
	);`,
		`CREATE TABLE IF NOT EXISTS task_columns (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		board_id INTEGER NOT NULL,
		name TEXT NOT NULL,
		position INTEGER NOT NULL,
		is_final INTEGER NOT NULL DEFAULT 0,
		wip_limit INTEGER,
		default_template_id INTEGER,
		is_active INTEGER NOT NULL DEFAULT 1,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		FOREIGN KEY(board_id) REFERENCES task_boards(id) ON DELETE CASCADE
	);`,
		`CREATE TABLE IF NOT EXISTS task_subcolumns (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		column_id INTEGER NOT NULL,
		name TEXT NOT NULL,
		position INTEGER NOT NULL,
		is_active INTEGER NOT NULL DEFAULT 1,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		FOREIGN KEY(column_id) REFERENCES task_columns(id) ON DELETE CASCADE
	);`,
	`CREATE TABLE IF NOT EXISTS tasks (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		board_id INTEGER NOT NULL,
		column_id INTEGER NOT NULL,
		subcolumn_id INTEGER,
		title TEXT NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		result TEXT NOT NULL DEFAULT '',
		external_link TEXT NOT NULL DEFAULT '',
		business_customer TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL DEFAULT '',
		priority TEXT NOT NULL,
		template_id INTEGER,
		recurring_rule_id INTEGER,
		checklist TEXT NOT NULL DEFAULT '[]',
		size_estimate INTEGER,
		created_by INTEGER,
		due_date TIMESTAMP,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		closed_at TIMESTAMP,
		is_archived INTEGER NOT NULL DEFAULT 0,
		position INTEGER NOT NULL DEFAULT 0,
		FOREIGN KEY(board_id) REFERENCES task_boards(id) ON DELETE CASCADE,
		FOREIGN KEY(column_id) REFERENCES task_columns(id) ON DELETE RESTRICT,
		FOREIGN KEY(subcolumn_id) REFERENCES task_subcolumns(id) ON DELETE SET NULL,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
	);`,
		`CREATE TABLE IF NOT EXISTS task_archive_entries (
		task_id INTEGER PRIMARY KEY,
		archived_at TIMESTAMP NOT NULL,
		archived_by INTEGER,
		archived_board_id INTEGER NOT NULL,
		archived_column_id INTEGER NOT NULL,
		archived_subcolumn_id INTEGER,
		original_position INTEGER NOT NULL DEFAULT 0,
		restored_at TIMESTAMP,
		restored_by INTEGER,
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(archived_by) REFERENCES users(id) ON DELETE SET NULL,
		FOREIGN KEY(restored_by) REFERENCES users(id) ON DELETE SET NULL
	);`,
		`CREATE TABLE IF NOT EXISTS task_assignments (
		task_id INTEGER NOT NULL,
		user_id INTEGER NOT NULL,
		assigned_at TIMESTAMP NOT NULL,
		assigned_by INTEGER,
		PRIMARY KEY(task_id, user_id),
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
		FOREIGN KEY(assigned_by) REFERENCES users(id) ON DELETE SET NULL
	);`,
		`CREATE TABLE IF NOT EXISTS task_comments (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		task_id INTEGER NOT NULL,
		author_id INTEGER NOT NULL,
		content TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL,
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE
	);`,
		`CREATE TABLE IF NOT EXISTS task_blocks (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		task_id INTEGER NOT NULL,
		block_type TEXT NOT NULL,
		reason TEXT,
		blocker_task_id INTEGER,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		resolved_by INTEGER,
		resolved_at TIMESTAMP,
		is_active INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(blocker_task_id) REFERENCES tasks(id) ON DELETE SET NULL,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
		FOREIGN KEY(resolved_by) REFERENCES users(id) ON DELETE SET NULL
	);`,
		`CREATE INDEX IF NOT EXISTS idx_task_boards_active ON task_boards(is_active);`,
		`CREATE INDEX IF NOT EXISTS idx_task_columns_board ON task_columns(board_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_columns_active ON task_columns(is_active);`,
		`CREATE INDEX IF NOT EXISTS idx_task_subcolumns_column ON task_subcolumns(column_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_subcolumns_active ON task_subcolumns(is_active);`,
		`CREATE INDEX IF NOT EXISTS idx_tasks_board ON tasks(board_id);`,
		`CREATE INDEX IF NOT EXISTS idx_tasks_column ON tasks(column_id);`,
		`CREATE INDEX IF NOT EXISTS idx_tasks_subcolumn ON tasks(subcolumn_id);`,
		`CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);`,
		`CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks(due_date);`,
		`CREATE INDEX IF NOT EXISTS idx_tasks_archived ON tasks(is_archived);`,
		`CREATE INDEX IF NOT EXISTS idx_task_archive_entries_archived_at ON task_archive_entries(archived_at);`,
		`CREATE INDEX IF NOT EXISTS idx_task_archive_entries_board ON task_archive_entries(archived_board_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_assignments_user ON task_assignments(user_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_assignments_task ON task_assignments(task_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_comments_task ON task_comments(task_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_blocks_task ON task_blocks(task_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_blocks_blocker ON task_blocks(blocker_task_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_blocks_active ON task_blocks(is_active);`,
		`CREATE TABLE IF NOT EXISTS task_files (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		task_id INTEGER NOT NULL,
		name TEXT NOT NULL,
		stored_name TEXT NOT NULL,
		content_type TEXT NOT NULL,
		size_bytes INTEGER NOT NULL,
		uploaded_by INTEGER,
		uploaded_at TIMESTAMP NOT NULL,
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(uploaded_by) REFERENCES users(id) ON DELETE SET NULL
	);`,
		`CREATE INDEX IF NOT EXISTS idx_task_files_task ON task_files(task_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_board_acl_board ON task_board_acl(board_id);`,
		`CREATE TABLE IF NOT EXISTS task_templates (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		board_id INTEGER NOT NULL,
		column_id INTEGER NOT NULL,
		title_template TEXT NOT NULL,
		description_template TEXT NOT NULL DEFAULT '',
		priority TEXT NOT NULL,
		default_assignees TEXT NOT NULL DEFAULT '[]',
		default_due_days INTEGER NOT NULL DEFAULT 0,
		checklist_template TEXT NOT NULL DEFAULT '[]',
		links_template TEXT NOT NULL DEFAULT '[]',
		is_active INTEGER NOT NULL DEFAULT 1,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		FOREIGN KEY(board_id) REFERENCES task_boards(id) ON DELETE CASCADE,
		FOREIGN KEY(column_id) REFERENCES task_columns(id) ON DELETE RESTRICT,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
	);`,
		`CREATE TABLE IF NOT EXISTS task_recurring_rules (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		template_id INTEGER NOT NULL,
		schedule_type TEXT NOT NULL,
		schedule_config TEXT NOT NULL DEFAULT '{}',
		time_of_day TEXT NOT NULL,
		next_run_at TIMESTAMP,
		last_run_at TIMESTAMP,
		is_active INTEGER NOT NULL DEFAULT 1,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		FOREIGN KEY(template_id) REFERENCES task_templates(id) ON DELETE CASCADE,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
	);`,
		`CREATE TABLE IF NOT EXISTS task_recurring_instances (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		rule_id INTEGER NOT NULL,
		template_id INTEGER NOT NULL,
		task_id INTEGER,
		scheduled_for TIMESTAMP NOT NULL,
		created_at TIMESTAMP NOT NULL,
		UNIQUE(rule_id, scheduled_for),
		FOREIGN KEY(rule_id) REFERENCES task_recurring_rules(id) ON DELETE CASCADE,
		FOREIGN KEY(template_id) REFERENCES task_templates(id) ON DELETE CASCADE,
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE SET NULL
	);`,
		`CREATE INDEX IF NOT EXISTS idx_task_templates_board ON task_templates(board_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_templates_active ON task_templates(is_active);`,
		`CREATE INDEX IF NOT EXISTS idx_task_recurring_rules_template ON task_recurring_rules(template_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_recurring_rules_active ON task_recurring_rules(is_active);`,
		`CREATE INDEX IF NOT EXISTS idx_task_recurring_rules_next_run ON task_recurring_rules(next_run_at);`,
		`CREATE INDEX IF NOT EXISTS idx_task_recurring_instances_rule ON task_recurring_instances(rule_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_recurring_instances_task ON task_recurring_instances(task_id);`,
		`CREATE TABLE IF NOT EXISTS task_spaces (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		organization_id TEXT NOT NULL DEFAULT '',
		name TEXT NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		layout TEXT NOT NULL DEFAULT 'row',
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		is_active INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
	);`,
		`CREATE TABLE IF NOT EXISTS task_space_acl (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		space_id INTEGER NOT NULL,
		subject_type TEXT NOT NULL,
		subject_id TEXT NOT NULL,
		permission TEXT NOT NULL,
		UNIQUE(space_id, subject_type, subject_id, permission),
		FOREIGN KEY(space_id) REFERENCES task_spaces(id) ON DELETE CASCADE
	);`,
		`CREATE INDEX IF NOT EXISTS idx_task_spaces_active ON task_spaces(is_active);`,
		`CREATE INDEX IF NOT EXISTS idx_task_space_acl_space ON task_space_acl(space_id);`,
		`CREATE TABLE IF NOT EXISTS task_tags (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL UNIQUE,
		created_at TIMESTAMP NOT NULL
	);`,
		`CREATE TABLE IF NOT EXISTS task_tag_links (
		task_id INTEGER NOT NULL,
		tag_id INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL,
		PRIMARY KEY(task_id, tag_id),
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(tag_id) REFERENCES task_tags(id) ON DELETE CASCADE
	);`,
		`CREATE INDEX IF NOT EXISTS idx_task_tag_links_task ON task_tag_links(task_id);`,
		`CREATE INDEX IF NOT EXISTS idx_task_tag_links_tag ON task_tag_links(tag_id);`,
		`CREATE TABLE IF NOT EXISTS task_board_layouts (
		user_id INTEGER NOT NULL,
		space_id INTEGER NOT NULL,
		layout_json TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		PRIMARY KEY(user_id, space_id),
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
		FOREIGN KEY(space_id) REFERENCES task_spaces(id) ON DELETE CASCADE
	);`,
		`CREATE INDEX IF NOT EXISTS idx_task_board_layouts_space ON task_board_layouts(space_id);`,
	}
}

func init() {
	migrations = append(migrations, taskMigrations()...)
}
